AWSTemplateFormatVersion: "2010-09-09"

Resources:
  TermProjectEC2Instance:
    Type: "AWS::EC2::Instance"
    Properties:
      InstanceType: t2.micro
      ImageId: YourImageId
      KeyName: ec2-key
      SecurityGroups:
        - !Ref InstanceSecurityGroup
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash -xe
          yum update -y
          yum install -y docker
          service docker start
          usermod -a -G docker ec2-user

  InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable SSH and TCP/3000 access
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 3000
          ToPort: 3000
          CidrIp: 0.0.0.0/0

Outputs:
  InstanceId:
    Description: Instance Id for EC2
    Value : !Ref TermProjectEC2Instance
  PublicIP:
    Description: Public IP for EC2
    Value: !GetAtt TermProjectEC2Instance.PublicIp
  
    